import React from 'react'
import Navbar from '../components/Navbar'

export const Explanation = () => {
  return (
    <div className="explanation">
      <Navbar />
      <div className="explanation__body">
        <h3>How the yarrow-stalk method works</h3>
        <p className="explanation__p">This is based on the explanation from Wilhelm’s translation. You can find his explanation <a href="https://www.taopage.org/iching/yarrow_stalks_method.html">here</a> and easy-to-follow instructions on divination by yarrow stalk <a href="https://www.instructables.com/Consult-the-I-Ching-with-Yarrow-Stalks/">here</a>.</p>
        <p className="explanation__p">You begin with 50 yarrow stalks and remove one, which is not used. This leaves you with 49. The 49 are divided into two bunches at random, one bunch for the left hand and one for the right hand. One stalk is removed from the right-hand bunch. Now we have 48 total between the two hands. Then we calculate modulo 4 (that is, what is the remainder when we divide a number by 4) for the left hand by removing bunches of 4 until we have a remainder that’s less than or equal to 4. This means that, if in our left hand was a number divisible by four, we’re left with 4, otherwise, we’re left with 1, 2, or 3. We do the same for the right hand. Then we add these to remainders to the 1 that we removed from the right hand.</p>
        <p className="explanation__p">Because the two bunches we had in the left and right hands added up to 48, which is divisible by 4, then the two remainders will also add up to 4, meaning we’re either going to have 3 + 1, 2 + 2, or 1 + 3, unless both left- and right-hand bunches we’re divisible by 4, in which case we’ll have 4 + 4, which will have 1 out of 4 times. We add this to the 1, meaning we’ll get 5 75% of the time and 9 25% of the time.</p>
        <p className="explanation__p">We then set aside this 5 or 9 and take the remaining stalks. Now, we’re left with either 40 or 44 stalks. We divide this into two random bunches, again. We remove 1, like before, meaning we have 39 or 43 stalks between the two hands. Then we calculate modulo 4, and just like before, if our remainder is 0, we take 4. For the second round, since modulo 4 for both 39 and 43 is 3, then the possibilities are 4 + 3, 2 + 1, 1 + 2, and 3 + 4, all equally probable. Adding this to the one we set aside, this means that 50% of the time, we get 8 and 50% of the time we get 4.</p>
        <p className="explanation__p">We remove this 4 or 8, and we do the same procedure with the remaining stalks, which will either be 32, 36, or 40. Again, we have a 50% chance of getting a 4 and a 50% chance of getting an 8.</p>
        <p className="explanation__p">Now we have what we need for calculating our first line. In practice, the first line is the bottom line. How we do so, is with the first bunch, if it’s a 5, we give it a value of 3. If it’s an 8, we give it a value of 2. For the bunches of 4 or 8, 4 counts as a 3, and 8 counts as 2. Then we sum up this set of 3s and 2s, which will give us a number between 6 and 9. If the value is odd (7 or 9), then it is a yang line, which is an unbroken line. If the number is even (6 or 8), then it is a yin (broken) line. In addition, we designate lines young and old. Young lines are unchanging lines and old lines are changing. 6 and 9 are both old, and 7 and 8 are both young. Hence, 6 = old yin, 7 = young yang, 8 = young yin, 9 = old yang.</p>
        <p className="explanation__p">Importantly, the odds of these four outcomes are not equal. Because we had only a 25% chance of getting a 2 on the first round and a 50% chance of getting 2s on the next two rounds, we can calculate the odds of getting a 6 (which only appears if we have 3 2s) as 0.25 * 0.5 * 0.5, which is 6.25%. Likewise, we can calculate the odds of 9, which requires 3 3s, since it would be 0.75 * 0.5 * 0.5, which is 18.75%. Calculating the 7 and 8 is a bit more complicated, but if we think about how in the second and third rounds, we’ll get 2 and 3 with equal probability, then we have 4 possibilities, all equally possible: 2 + 2, 2 + 3, 3 + 2, and 3 + 3. Hence, we’ll get 4 25% of the time, 5 50% of the time, and 6 25% of the time. To get a 7, we need a 2 + 5 or a 3 + 4. 2 in the first round we get 25% of the time, so 2 + 5 equals 0.25 * 0.5, which is 12.5%. 3 in the first round occurs 75% of the time, so 3 + 4 equals 0.75 * 0.25, which is 18.75%. 18.75% + 12.5% = 31.25%. We can calculate 8 the same way, which we either get with either 3 + 5 or 2 + 6. 3 + 5 equals 0.75 * 0.5, which quals 37.5%, and 2 + 6 equals 0.25 * 0.25, which equals 6.25%. 37.5% + 6.25% equals 43.75.</p>
        <p className="explanation__p">In summary, 6: 6.25% (1/16), 7: 31.25% (5/16), 8: 43.75% (7/16) and 9: 18.75% (3/16).</p>
        <p className="explanation__p">This does mean that half the time we’ll get yin half the time (6.25% + 43.75% = 50%) and yang half the time (31.25% + 18.75? = 50%), which makes all 64 hexagrams equally likely. However, the odds of getting a changing line vary. We’ll get a changing line 25% of the time, but old yang is three times as likely as old yin, and young yin is more common than young yang.</p>
      </div>
    </div>
  )
}
